name: Release Build

on: workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
    - name: Test tool paths
      run: qmake
