name: Release Build

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
    - name: Run build
      run: bash ./build.sh
    - name: Archive resulting executable
      uses: actions/upload-artifact@v4
      with:
        name: TotkArmorTracker_Linux
        path: ./bin/**/*

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
    - name: Run build
      run: ./build.bat
    - name: Archive resulting executable
      uses: actions/upload-artifact@v4
      with:
        name: TotkArmorTracker_Windows
        path: ./bin/release/**/*
