name: Release Build

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if branch is not main
      if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
      run: |
        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
        exit 1
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
    - name: Run build
      run: bash ./build.sh --compress
    - name: Archive resulting package
      uses: actions/upload-artifact@v4
      with:
        name: linux
        path: ./totkArmorTracker_linux.zip

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Fail if branch is not main
      if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
      run: |
        echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
        exit 1
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
    - name: Run build
      run: ./build.bat --compress
    - name: Archive resulting package
      uses: actions/upload-artifact@v4
      with:
        name: windows
        path: ./totkArmorTracker_windows.zip
