name: Release Build

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Create bin dir
      run: mkdir bin
      
    - name: Run qmake
      run: qmake ../project/TotkArmorTracker.pro -spec linux-g++ CONFIG+=qtquickcompiler
      working-directory: ./bin

    - name: Build project
      run: make -j
      working-directory: ./bin

    - name: Archive resulting executable
      uses: actions/upload-artifact@v4
      with:
        name: TotkArmorTracker_Linux
        path: ./bin/**/*

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        tools: 'tools_qtcreator,qt.tools.qtcreator'

    - name: Set up MSVC paths
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Create bin dir
      run: mkdir bin

    - name: Run qmake
      run: qmake ../project/TotkArmorTracker.pro -spec win32-msvc "CONFIG+=qtquickcompiler"
      working-directory: ./bin

    - name: Prepare make file
      run: ../../Qt/Tools/QtCreator/bin/jom.exe -f Makefile qmake_all
      working-directory: ./bin

    - name: Build project
      run: ../../Qt/Tools/QtCreator/bin/jom.exe
      working-directory: ./bin

    - name: Bundle required dlls and added files
      run: |
        copy ../*.xml .
        windeployqt ./TotkArmorTracker.exe --qmldir ../../project
      working-directory: ./bin/release

    - name: Archive resulting executable
      uses: actions/upload-artifact@v4
      with:
        name: TotkArmorTracker_Windows
        path: ./bin/release/**/*
